---
- name: Install Packages
  xbps:
    pkg: caddy
    state: present

- name: Create Drop-In Directory
  file:
    path: /etc/caddy/conf.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create logs directory
  file:
    path: /var/log/caddy
    state: directory
    owner: caddy
    group: caddy
    mode: 0755

- name: Write Base Config
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: 0644
  notify:
    - caddy

- name: Install Firewall Rules
  template:
    src: caddy.rules.j2
    dest: /etc/iptables.d/caddy.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Enable Service
  service:
    name: caddy
    state: started
    enabled: true
